[package]
name = "kival-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
# Vendor
argx.workspace = true
eyre.workspace = true
libc.workspace = true
tokio = { workspace = true, features = ["signal"] }

# Crates
kival-tasks.workspace = true
kival-tracing.workspace = true
