import type { CSSProperties } from "react";
import { colors, fontFamilies, shadows } from "./constants";

export const apiKeysStyles: Record<string, CSSProperties> = {
  apiKeysPage: {
    width: "100%",
    minWidth: 0,
    height: "100%",
    padding: "42px 48px",
    overflowY: "auto",
    background: colors.surface,
    boxSizing: "border-box",
  },
  apiKeyCreateCard: {
    padding: 24,
    border: `1px solid ${colors.border}`,
    borderRadius: 8,
    background: colors.surface,
    boxShadow: "none",
  },
  apiKeySectionHeader: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 20,
    marginBottom: 20,
  },
  apiKeySectionTitle: {
    margin: "0 0 5px",
    color: colors.text,
    fontSize: 20,
    lineHeight: 1.3,
    letterSpacing: "-0.025em",
  },
  apiKeyForm: {
    display: "flex",
    flexDirection: "column",
    gap: 24,
  },
  apiKeyFormGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))",
    gap: 16,
  },
  apiKeyFieldset: {
    minWidth: 0,
    margin: 0,
    padding: 0,
    border: 0,
  },
  apiKeyLegend: {
    padding: 0,
    color: colors.text,
    fontSize: 14,
    fontWeight: 700,
    fontFamily: fontFamilies.mono,
  },
  apiKeyHelp: {
    display: "block",
    margin: "5px 0 12px",
    color: colors.textMuted,
    fontSize: 13,
    lineHeight: 1.45,
  },
  apiKeyScopeToggle: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 20,
    marginTop: 10,
    padding: "12px 14px",
    border: `1px solid ${colors.borderStrong}`,
    borderRadius: 8,
    background: colors.surfaceSubtle,
    color: colors.textMuted,
    textAlign: "left",
    font: "inherit",
    fontSize: 12,
    cursor: "pointer",
  },
  apiKeyScopeToggleCopy: {
    display: "flex",
    flexDirection: "column",
    gap: 3,
    color: colors.textMuted,
    lineHeight: 1.4,
  },
  apiKeyOptionGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(245px, 1fr))",
    gap: 8,
  },
  apiKeyOption: {
    display: "flex",
    alignItems: "flex-start",
    gap: 10,
    padding: 12,
    border: `1px solid ${colors.border}`,
    borderRadius: 8,
    background: colors.surface,
    color: colors.text,
    cursor: "pointer",
  },
  apiKeyOptionSelected: {
    display: "flex",
    alignItems: "flex-start",
    gap: 10,
    padding: 12,
    border: `1px solid ${colors.accentMuted}`,
    borderRadius: 8,
    background: colors.surfaceSubtle,
    color: colors.text,
    cursor: "pointer",
  },
  apiKeyOptionCopy: {
    display: "flex",
    flexDirection: "column",
    gap: 3,
    color: colors.textMuted,
    fontSize: 12,
    lineHeight: 1.4,
  },
  apiKeyWorkspaceGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))",
    gap: 8,
  },
  apiKeyWorkspaceOption: {
    display: "flex",
    alignItems: "center",
    gap: 9,
    padding: "9px 11px",
    border: `1px solid ${colors.border}`,
    borderRadius: 8,
    background: colors.surfaceSubtle,
    color: colors.text,
    fontSize: 13,
    cursor: "pointer",
  },
  apiKeyWorkspaceOptionSelected: {
    display: "flex",
    alignItems: "center",
    gap: 9,
    padding: "9px 11px",
    border: `1px solid ${colors.accentMuted}`,
    borderRadius: 8,
    background: colors.surfaceSubtle,
    color: colors.text,
    fontSize: 13,
    cursor: "pointer",
  },
  apiKeySelectAllOption: {
    display: "flex",
    alignItems: "flex-start",
    gap: 10,
    margin: "10px 0 12px",
    padding: "11px 12px",
    border: `1px solid ${colors.borderStrong}`,
    borderRadius: 8,
    background: colors.surfaceSubtle,
    color: colors.text,
    cursor: "pointer",
  },
  apiKeyHelpInline: {
    display: "block",
    marginTop: 2,
    color: colors.textMuted,
    fontSize: 12,
    lineHeight: 1.4,
  },
  apiKeyFormActions: {
    display: "flex",
    justifyContent: "flex-end",
    paddingTop: 2,
  },
  apiKeyListSection: {
    marginTop: 42,
  },
  apiKeyGroupedLists: {
    display: "flex",
    flexDirection: "column",
    gap: 16,
  },
  apiKeyRevokedDetails: {
    border: `1px solid ${colors.border}`,
    borderRadius: 8,
    background: colors.surfaceSubtle,
    color: colors.textMuted,
  },
  apiKeyRevokedSummary: {
    padding: "12px 14px",
    cursor: "pointer",
    fontSize: 13,
    fontWeight: 700,
  },
  apiKeyRevokedCount: {
    marginLeft: 8,
    padding: "2px 7px",
    borderRadius: 8,
    background: colors.surfaceMuted,
    color: colors.textSubtle,
    fontSize: 11,
  },
  apiKeyRevokedContent: {
    padding: "0 12px 12px",
  },
  apiKeyList: {
    display: "flex",
    flexDirection: "column",
    gap: 0,
  },
  apiKeyCard: {
    padding: 18,
    border: `1px solid ${colors.border}`,
    borderRadius: 8,
    background: colors.surface,
  },
  apiKeyCardHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 16,
    marginBottom: 15,
  },
  apiKeyCardTitle: {
    minWidth: 0,
    display: "flex",
    alignItems: "center",
    gap: 9,
    color: colors.text,
  },
  apiKeyStatus: {
    padding: "3px 7px",
    borderRadius: 8,
    background: colors.surfaceMuted,
    color: colors.textMuted,
    fontSize: 11,
    fontWeight: 700,
  },
  apiKeyStatusMuted: {
    padding: "3px 7px",
    borderRadius: 8,
    background: colors.dangerSurface,
    color: colors.danger,
    fontSize: 11,
    fontWeight: 700,
  },
  apiKeyMetadata: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(130px, 1fr))",
    gap: 12,
    margin: "0 0 15px",
    color: colors.textMuted,
    fontSize: 12,
  },
  apiKeyRestrictions: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    gap: 7,
  },
  apiKeyRestrictionLabel: {
    marginTop: 2,
    color: colors.textSubtle,
    fontSize: 10,
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: "0.07em",
    fontFamily: fontFamilies.mono,
  },
  apiKeyPills: {
    display: "flex",
    flexWrap: "wrap",
    gap: 6,
  },
  apiKeyPill: {
    padding: "4px 7px",
    border: `1px solid ${colors.border}`,
    borderRadius: 8,
    background: colors.surfaceSubtle,
    color: colors.textMuted,
    fontSize: 11,
  },
  apiKeyDangerButton: {
    minHeight: 32,
    padding: "0 11px",
    border: `1px solid ${colors.dangerBorder}`,
    borderRadius: 8,
    background: colors.dangerSurface,
    color: colors.danger,
    font: "inherit",
    fontSize: 12,
    fontWeight: 700,
    cursor: "pointer",
  },
  apiKeyDangerButtonSolid: {
    minHeight: 36,
    padding: "0 14px",
    border: 0,
    borderRadius: 8,
    background: colors.danger,
    color: colors.textOnStrong,
    font: "inherit",
    fontSize: 14,
    fontWeight: 700,
    cursor: "pointer",
  },
  apiKeyEmpty: {
    padding: 28,
    border: `1px dashed ${colors.borderStrong}`,
    borderRadius: 8,
    color: colors.textMuted,
    textAlign: "center",
  },
  apiKeySecretDialog: {
    position: "relative",
    zIndex: 1,
    width: "min(100%, 620px)",
    display: "flex",
    flexDirection: "column",
    gap: 20,
    padding: 24,
    border: `1px solid ${colors.border}`,
    borderRadius: 8,
    background: colors.surface,
    boxShadow: shadows.large,
  },
  apiKeySecret: {
    display: "block",
    maxHeight: 180,
    overflow: "auto",
    padding: 14,
    border: `1px solid ${colors.borderStrong}`,
    borderRadius: 8,
    background: colors.surfaceSubtle,
    color: colors.text,
    fontFamily: fontFamilies.mono,
    fontSize: 13,
    lineHeight: 1.5,
    overflowWrap: "anywhere",
    userSelect: "all",
  },
};
