import type { CSSProperties } from "react";
import { colors, fontFamilies } from "./constants";

export const authStyles: Record<string, CSSProperties> = {
  loadingPage: {
    minHeight: "100vh",
    display: "grid",
    placeItems: "center",
    background: colors.background,
    color: colors.text,
  },
  loginPage: {
    minHeight: "100vh",
    display: "grid",
    placeItems: "center",
    padding: 32,
    background: colors.background,
  },
  loginShell: {
    width: "100%",
    maxWidth: 980,
    minHeight: 560,
    display: "grid",
    gridTemplateColumns: "minmax(0, 1.05fr) minmax(360px, 0.95fr)",
    overflow: "hidden",
    border: `1px solid ${colors.border}`,
    borderRadius: 8,
    background: colors.surface,
    boxShadow: "none",
  },
  loginIntro: {
    minWidth: 0,
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    padding: 42,
    background: colors.surfaceStrong,
    color: colors.textOnStrong,
  },
  loginIntroCopy: {
    maxWidth: 430,
    display: "flex",
    flexDirection: "column",
    gap: 16,
  },
  loginEyebrow: {
    color: colors.textOnStrong,
    opacity: 0.68,
    fontFamily: fontFamilies.mono,
    fontSize: 12,
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: "0.1em",
  },
  loginHeadline: {
    maxWidth: 380,
    fontSize: 48,
    lineHeight: 1.02,
    fontFamily: fontFamilies.display,
    fontWeight: 400,
    letterSpacing: "-0.035em",
  },
  loginDescription: {
    maxWidth: 420,
    color: colors.textOnStrong,
    opacity: 0.72,
    fontSize: 16,
    lineHeight: 1.65,
  },
  loginPanel: {
    display: "grid",
    placeItems: "center",
    padding: 48,
  },
  loginCard: {
    width: "100%",
    maxWidth: 360,
    display: "flex",
    flexDirection: "column",
    gap: 24,
  },
  loginCardHeader: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
  },
  loginTitle: {
    fontSize: 28,
    lineHeight: 1.15,
    fontFamily: fontFamilies.display,
    fontWeight: 500,
    letterSpacing: "-0.02em",
  },
  loginFields: {
    display: "flex",
    flexDirection: "column",
    gap: 18,
  },
  fieldLabel: {
    color: colors.textMuted,
    fontFamily: fontFamilies.mono,
    fontSize: 11,
    fontWeight: 500,
    letterSpacing: "0.05em",
    textTransform: "uppercase",
  },
  fieldHint: {
    marginTop: -2,
    color: colors.textSubtle,
    fontSize: 12,
    lineHeight: 1.4,
  },
  loginError: {
    padding: "10px 12px",
    border: `1px solid ${colors.dangerBorder}`,
    borderRadius: 8,
    background: colors.dangerSurface,
    color: colors.dangerStrong,
    fontSize: 13,
    lineHeight: 1.45,
  },
  field: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    fontSize: 14,
  },
  input: {
    height: 42,
    padding: "0 12px",
    borderRadius: 8,
    border: `1px solid ${colors.borderStrong}`,
    background: colors.surface,
    color: colors.text,
    font: "inherit",
    fontSize: 15,
    outline: "none",
  },
  primaryButton: {
    height: 42,
    border: 0,
    borderRadius: 8,
    background: colors.buttonPrimary,
    color: colors.textOnStrong,
    font: "inherit",
    fontWeight: 600,
    fontFamily: fontFamilies.mono,
    fontSize: 12,
    letterSpacing: "0.04em",
    textTransform: "uppercase",
    cursor: "pointer",
  },
  authTextLink: {
    alignSelf: "center",
    color: colors.textMuted,
    fontSize: 13,
    fontWeight: 600,
    textDecoration: "underline",
    textUnderlineOffset: 3,
  },
  primaryButtonCompact: {
    minHeight: 36,
    padding: "0 14px",
    border: 0,
    borderRadius: 8,
    background: colors.buttonPrimary,
    color: colors.textOnStrong,
    font: "inherit",
    fontSize: 14,
    fontWeight: 600,
    cursor: "pointer",
  },
  secondaryButton: {
    minHeight: 36,
    padding: "0 14px",
    border: `1px solid ${colors.borderStrong}`,
    borderRadius: 8,
    background: colors.surface,
    color: colors.textMuted,
    font: "inherit",
    fontSize: 14,
    fontWeight: 600,
    cursor: "pointer",
  },
  error: {
    margin: 0,
    color: colors.danger,
    lineHeight: 1.5,
  },
  errorBox: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
    padding: 16,
    marginBottom: 20,
    border: `1px solid ${colors.dangerBorder}`,
    borderRadius: 8,
    background: colors.dangerSurface,
    color: colors.dangerStrong,
  },
  secondaryButtonCompact: {
    padding: "5px 9px",
    border: `1px solid ${colors.borderStrong}`,
    borderRadius: 8,
    background: colors.surface,
    color: colors.textMuted,
    font: "inherit",
    fontSize: 12,
    cursor: "pointer",
  },
};
