import type { CSSProperties } from "react";
import { colors, fontFamilies, shadows } from "./constants";

export const baseStyles: Record<string, CSSProperties> = {
  app: {
    height: "100vh",
    minHeight: 0,
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
    background: colors.background,
    color: colors.text,
    fontFamily: fontFamilies.sans,
  },
  muted: {
    margin: 0,
    color: colors.textMuted,
    lineHeight: 1.5,
  },
  copyableId: {
    width: "fit-content",
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    padding: 0,
    border: 0,
    background: colors.transparent,
    color: colors.textSubtle,
    font: "inherit",
    fontSize: 13,
    textAlign: "left",
    cursor: "pointer",
    pointerEvents: "auto",
  },
  copyableIdFeedback: {
    color: colors.textMuted,
    fontSize: "0.92em",
  },
  profileHoverName: {
    position: "relative",
    display: "inline-flex",
    padding: 0,
    border: 0,
    background: colors.transparent,
    color: "inherit",
    font: "inherit",
    outline: "none",
    cursor: "default",
    pointerEvents: "auto",
  },
  favoriteButton: {
    width: 28,
    height: 28,
    display: "grid",
    placeItems: "center",
    padding: 0,
    border: 0,
    background: colors.transparent,
    color: colors.accent,
    fontSize: 18,
    lineHeight: 1,
    cursor: "pointer",
    pointerEvents: "auto",
  },
  pinButton: {
    width: 28,
    height: 28,
    display: "grid",
    alignItems: "center",
    justifyContent: "center",
    padding: 0,
    border: 0,
    background: colors.transparent,
    color: colors.textMuted,
    font: "inherit",
    cursor: "pointer",
    pointerEvents: "auto",
  },
  pinButtonActive: {
    width: 28,
    height: 28,
    display: "grid",
    alignItems: "center",
    justifyContent: "center",
    padding: 0,
    border: 0,
    background: colors.transparent,
    color: colors.accent,
    cursor: "pointer",
    pointerEvents: "auto",
  },
  profileHoverCard: {
    position: "absolute",
    top: "calc(100% + 8px)",
    zIndex: 40,
    minWidth: 180,
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    gap: 2,
    padding: "9px 10px",
    border: `1px solid ${colors.border}`,
    borderRadius: 8,
    background: colors.surface,
    color: colors.text,
    boxShadow: shadows.medium,
    fontWeight: 400,
    lineHeight: 1.3,
    textAlign: "left",
    pointerEvents: "none",
  },
  profileHoverCardName: {
    maxWidth: 220,
    overflow: "hidden",
    fontSize: 13,
    fontWeight: 700,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  profileHoverCardMeta: {
    maxWidth: 220,
    overflow: "hidden",
    color: colors.textMuted,
    fontSize: 12,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  profileHoverCardDetail: {
    marginTop: 5,
    color: colors.textSubtle,
    fontSize: 11,
  },
  profileHoverCardRoles: {
    width: "100%",
    display: "flex",
    flexDirection: "column",
    gap: 5,
    marginTop: 7,
    paddingTop: 7,
    borderTop: `1px solid ${colors.border}`,
  },
  profileHoverCardRole: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 14,
    whiteSpace: "nowrap",
  },
  profileHoverCardRoleLabel: {
    color: colors.textMuted,
    fontSize: 11,
  },
  profileHoverCardRoleValue: {
    color: colors.text,
    fontSize: 11,
    fontWeight: 600,
  },
  infiniteScrollSentinel: {
    minHeight: 32,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "8px 0",
    color: colors.textMuted,
    fontSize: 12,
  },
  toast: {
    position: "fixed",
    right: 22,
    bottom: 22,
    zIndex: 1200,
    display: "flex",
    alignItems: "center",
    gap: 9,
    maxWidth: 360,
    padding: "11px 12px",
    border: `1px solid ${colors.borderStrong}`,
    borderRadius: 8,
    background: colors.surfaceStrong,
    color: colors.textOnStrong,
    boxShadow: shadows.medium,
    fontSize: 13,
  },
  toastDismiss: {
    marginLeft: 4,
    padding: 0,
    border: 0,
    background: colors.transparent,
    color: colors.textOnStrong,
    opacity: 0.68,
    font: "inherit",
    fontSize: 18,
    lineHeight: 1,
    cursor: "pointer",
  },
};
