import type { CSSProperties } from "react";
import { colors, fontFamilies, layout } from "./constants";

export const editorStyles: Record<string, CSSProperties> = {
  editorForm: {
    width: "100%",
    maxWidth: layout.editorMaxWidth,
    display: "flex",
    flexDirection: "column",
    gap: 20,
  },
  editorHeader: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 24,
    marginBottom: 12,
  },
  editorActions: {
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  editorTextarea: {
    width: "100%",
    minHeight: 360,
    padding: 14,
    borderRadius: 8,
    border: `1px solid ${colors.borderStrong}`,
    background: colors.surface,
    color: colors.text,
    font: "inherit",
    fontSize: 15,
    lineHeight: 1.6,
    outline: "none",
    boxSizing: "border-box",
  },
  markdownEditor: {
    width: "100%",
    overflow: "visible",
    border: `1px solid ${colors.borderStrong}`,
    borderRadius: 8,
    background: colors.surface,
  },
  markdownEditorFullscreen: {
    position: "fixed",
    zIndex: 1000,
    inset: 12,
    width: "auto",
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
    boxShadow: "0 0 0 100vmax rgba(12, 18, 28, 0.42), 0 18px 54px rgba(0, 0, 0, 0.22)",
  },
  markdownEditorTopBar: {
    minHeight: 42,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    padding: "5px 7px",
    borderBottom: `1px solid ${colors.border}`,
    borderRadius: "8px 8px 0 0",
    background: colors.surfaceSubtle,
  },
  markdownToolbar: {
    minWidth: 0,
    display: "flex",
    alignItems: "center",
    gap: 2,
    overflow: "visible",
  },
  markdownToolbarButton: {
    minWidth: 30,
    height: 30,
    padding: "0 7px",
    border: 0,
    borderRadius: 8,
    background: colors.transparent,
    color: colors.textMuted,
    font: "inherit",
    fontSize: 12,
    fontWeight: 600,
    cursor: "pointer",
  },
  markdownToolbarButtonActive: {
    background: colors.surfaceMuted,
    color: colors.text,
  },
  markdownHeadingControl: {
    position: "relative",
    flexShrink: 0,
  },
  markdownHeadingTrigger: {
    minWidth: 45,
    height: 30,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
    padding: "0 7px",
    border: `1px solid ${colors.border}`,
    borderRadius: 8,
    background: colors.surface,
    color: colors.textMuted,
    cursor: "pointer",
  },
  markdownHeadingMenu: {
    position: "absolute",
    zIndex: 30,
    top: "calc(100% + 5px)",
    left: 0,
    display: "grid",
    gridTemplateColumns: "repeat(3, 32px)",
    gap: 3,
    padding: 5,
    border: `1px solid ${colors.border}`,
    borderRadius: 8,
    background: colors.surface,
    boxShadow: "0 8px 22px rgba(0, 0, 0, 0.16)",
  },
  markdownHeadingOption: {
    width: 32,
    height: 30,
    display: "inline-grid",
    placeItems: "center",
    padding: 0,
    border: 0,
    borderRadius: 6,
    background: colors.transparent,
    color: colors.textMuted,
    cursor: "pointer",
  },
  markdownModeSwitch: {
    flexShrink: 0,
    display: "flex",
    alignItems: "center",
    padding: 2,
    border: `1px solid ${colors.border}`,
    borderRadius: 8,
    background: colors.surface,
  },
  markdownEditorViewControls: {
    flexShrink: 0,
    display: "flex",
    alignItems: "center",
    gap: 4,
  },
  markdownModeButton: {
    padding: "4px 8px",
    border: 0,
    borderRadius: 8,
    background: colors.transparent,
    color: colors.textMuted,
    font: "inherit",
    fontSize: 12,
    cursor: "pointer",
  },
  markdownModeButtonActive: {
    background: colors.surfaceSubtle,
    color: colors.text,
    fontWeight: 600,
  },
  markdownAttachmentError: {
    padding: "8px 12px",
    borderBottom: `1px solid ${colors.dangerBorder}`,
    background: colors.dangerSurface,
    color: colors.dangerStrong,
    fontSize: 13,
  },
  markdownEditorSurface: {
    minHeight: layout.markdownEditorMinHeight,
  },
  markdownEditorSurfaceSplit: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) minmax(0, 1fr)",
  },
  markdownEditorSurfaceFullscreen: {
    flex: 1,
    minHeight: 0,
    overflow: "hidden",
  },
  markdownTextarea: {
    width: "100%",
    minHeight: layout.markdownEditorMinHeight,
    padding: "22px 24px",
    resize: "vertical",
    border: 0,
    borderRadius: "0 0 8px 8px",
    background: colors.surface,
    color: colors.text,
    fontFamily: fontFamilies.mono,
    fontSize: 14,
    lineHeight: 1.7,
    outline: "none",
    boxSizing: "border-box",
  },
  markdownTextareaSplit: {
    resize: "none",
    borderRight: `1px solid ${colors.border}`,
    borderRadius: "0 0 0 8px",
  },
  markdownTextareaFullscreen: {
    height: "100%",
    minHeight: 0,
    resize: "none",
    overflowY: "auto",
  },
  markdownPreview: {
    minHeight: layout.markdownEditorMinHeight,
    padding: "22px 28px",
    color: colors.text,
    fontSize: 16,
    lineHeight: 1.7,
    boxSizing: "border-box",
  },
  markdownPreviewSplit: {
    minWidth: 0,
    maxHeight: 620,
    overflowY: "auto",
  },
  markdownPreviewFullscreen: {
    height: "100%",
    minHeight: 0,
    maxHeight: "none",
    overflowY: "auto",
  },
  markdownPreviewEmpty: {
    margin: 0,
    color: colors.textSubtle,
  },
};
