import type { CSSProperties } from "react";
import { colors, shadows } from "./constants";

export const graphStyles: Record<string, CSSProperties> = {
  graphPage: {
    width: "100%",
    height: "100%",
    minWidth: 0,
    display: "flex",
    flexDirection: "column",
  },
  graphViewport: {
    position: "relative",
    width: "100%",
    height: "100%",
    minHeight: 0,
    flex: 1,
    overflow: "hidden",
    background: colors.surfaceSubtle,
    cursor: "grab",
    userSelect: "none",
  },
  graphCanvas: {
    position: "absolute",
    inset: 0,
    width: "100%",
    height: "100%",
    display: "block",
  },
  graphOverlay: {
    position: "absolute",
    inset: 0,
    width: "100%",
    height: "100%",
    display: "block",
    pointerEvents: "none",
  },
  graphTooltip: {
    position: "absolute",
    zIndex: 4,
    maxWidth: 260,
    padding: "8px 10px",
    border: `1px solid ${colors.border}`,
    borderRadius: 8,
    background: colors.glassStrong,
    boxShadow: shadows.small,
    color: colors.text,
    fontSize: 12,
    lineHeight: 1.4,
    pointerEvents: "none",
  },
  graphTooltipMeta: {
    display: "block",
    marginTop: 2,
    color: colors.textSubtle,
  },
  graphDebug: {
    position: "absolute",
    right: 14,
    bottom: 12,
    zIndex: 3,
    maxWidth: "60%",
    padding: "6px 8px",
    borderRadius: 8,
    background: colors.surfaceStrong,
    color: colors.textOnStrong,
    fontSize: 11,
    lineHeight: 1.4,
    pointerEvents: "none",
  },
  graphHint: {
    position: "absolute",
    left: 14,
    bottom: 12,
    zIndex: 3,
    padding: "6px 8px",
    borderRadius: 8,
    background: colors.glass,
    color: colors.textSubtle,
    fontSize: 11,
    pointerEvents: "none",
  },
  localGraphRevealButton: {
    position: "absolute",
    top: 8,
    right: 8,
    zIndex: 4,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: 30,
    height: 30,
    padding: 0,
    border: `1px solid ${colors.borderStrong}`,
    borderRadius: 8,
    background: colors.glass,
    color: colors.textMuted,
    cursor: "pointer",
    boxShadow: shadows.small,
    backdropFilter: "blur(6px)",
  },
  localGraphBlock: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    padding: "16px 10px",
    borderBottom: `1px solid ${colors.surfaceMuted}`,
  },
  localGraphViewport: {
    position: "relative",
    width: "100%",
    height: 220,
    overflow: "hidden",
    border: `1px solid ${colors.surfaceMuted}`,
    borderRadius: 8,
    background: colors.surfaceSubtle,
    cursor: "default",
    touchAction: "none",
  },
  localGraphCanvas: {
    position: "absolute",
    inset: 0,
    width: "100%",
    height: "100%",
    display: "block",
  },
  localGraphOverlay: {
    position: "absolute",
    inset: 0,
    width: "100%",
    height: "100%",
    display: "block",
    pointerEvents: "none",
  },
  localGraphHint: {
    color: colors.textSubtle,
    fontSize: 11,
    lineHeight: 1.4,
  },
};
