import type { CSSProperties } from "react";
import { colors, fontFamilies } from "./constants";

export const inboxStyles: Record<string, CSSProperties> = {
  inboxPage: {
    minWidth: 0,
    flex: 1,
    overflowY: "auto",
  },
  inboxContent: {
    width: "min(100%, 1040px)",
    minHeight: "100%",
    margin: "0 auto",
    padding: "38px 40px 64px",
    boxSizing: "border-box",
  },
  inboxToolbar: {
    display: "flex",
    alignItems: "flex-end",
    justifyContent: "space-between",
    gap: 18,
    marginBottom: 24,
  },
  inboxFilters: {
    display: "flex",
    alignItems: "flex-end",
    flexWrap: "wrap",
    gap: 12,
  },
  inboxList: {
    display: "flex",
    flexDirection: "column",
    border: `1px solid ${colors.borderStrong}`,
    borderRadius: 8,
    overflow: "hidden",
  },
  inboxItem: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) auto",
    alignItems: "center",
    gap: 8,
    borderBottom: `1px solid ${colors.borderStrong}`,
    background: colors.transparent,
  },
  inboxItemUnread: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) auto",
    alignItems: "center",
    gap: 8,
    borderBottom: `1px solid ${colors.borderStrong}`,
    background: colors.surfaceSubtle,
  },
  inboxItemMain: {
    minWidth: 0,
    display: "grid",
    gridTemplateColumns: "18px minmax(0, 1fr)",
    alignItems: "center",
    gap: 10,
    padding: "10px 12px",
    border: 0,
    background: colors.transparent,
    color: colors.text,
    textAlign: "left",
    font: "inherit",
    cursor: "pointer",
  },
  inboxItemMainRead: {
    minWidth: 0,
    display: "grid",
    gridTemplateColumns: "18px minmax(0, 1fr)",
    alignItems: "center",
    gap: 10,
    padding: "10px 12px",
    border: 0,
    background: colors.transparent,
    color: colors.textMuted,
    textAlign: "left",
    font: "inherit",
    cursor: "pointer",
  },
  inboxReasonIcon: {
    width: 18,
    height: 18,
    display: "grid",
    placeItems: "center",
    color: colors.textSubtle,
  },
  inboxReasonIconUnread: {
    width: 18,
    height: 18,
    display: "grid",
    placeItems: "center",
    color: colors.accent,
  },
  inboxReasonAt: {
    fontFamily: fontFamilies.mono,
    fontSize: 16,
    fontWeight: 700,
    lineHeight: 1,
  },
  inboxItemCopy: {
    minWidth: 0,
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    gap: 2,
  },
  inboxItemHeading: {
    width: "100%",
    minWidth: 0,
    maxWidth: "100%",
    display: "flex",
    alignItems: "center",
    gap: 7,
    fontSize: 13,
    lineHeight: 1.3,
  },
  inboxItemTitle: {
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  inboxUnreadDot: {
    width: 7,
    height: 7,
    flexShrink: 0,
    borderRadius: "50%",
    background: colors.accent,
  },
  inboxItemDetail: {
    display: "block",
    maxWidth: "100%",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    color: colors.textMuted,
    fontSize: 12,
    lineHeight: 1.35,
  },
  inboxItemMeta: {
    color: colors.textSubtle,
    fontFamily: fontFamilies.mono,
    fontSize: 10,
  },
  inboxReadButton: {
    width: 30,
    height: 30,
    display: "grid",
    placeItems: "center",
    padding: 0,
    border: `1px solid ${colors.border}`,
    borderRadius: 6,
    background: colors.transparent,
    color: colors.textMuted,
    font: "inherit",
    fontSize: 12,
    cursor: "pointer",
  },
  inboxItemActions: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    marginRight: 10,
  },
  inboxItemTime: {
    minWidth: 28,
    color: colors.textSubtle,
    fontFamily: fontFamilies.mono,
    fontSize: 10,
    textAlign: "right",
  },
  inboxSavingDots: {
    fontSize: 8,
    letterSpacing: 1,
  },
  inboxEmpty: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
    padding: "28px 0",
    color: colors.textMuted,
    borderTop: `1px solid ${colors.borderStrong}`,
    borderBottom: `1px solid ${colors.borderStrong}`,
  },
};
