import type { CSSProperties } from "react";
import { colors, fontFamilies } from "./constants";

export const markdownStyles: Record<string, CSSProperties> = {
  markdownBody: {
    overflowWrap: "anywhere",
  },
  markdownParagraph: {
    margin: "0 0 16px",
  },
  markdownH1: {
    margin: "28px 0 14px",
    fontSize: 30,
    lineHeight: 1.2,
    fontWeight: 700,
    letterSpacing: "-0.025em",
  },
  markdownH2: {
    margin: "26px 0 12px",
    fontSize: 23,
    lineHeight: 1.3,
    fontWeight: 700,
    letterSpacing: "-0.015em",
  },
  markdownH3: {
    margin: "22px 0 10px",
    fontSize: 18,
    lineHeight: 1.4,
    fontWeight: 650,
  },
  markdownH4: {
    margin: "20px 0 8px",
    fontSize: 16,
    lineHeight: 1.45,
    fontWeight: 650,
  },
  markdownH5: {
    margin: "18px 0 8px",
    fontSize: 15,
    lineHeight: 1.45,
    fontWeight: 650,
  },
  markdownH6: {
    margin: "18px 0 8px",
    fontSize: 14,
    lineHeight: 1.45,
    fontWeight: 650,
    color: colors.textMuted,
  },
  markdownLink: {
    color: colors.accent,
    textDecoration: "underline",
    textDecorationColor: colors.accentMuted,
    textUnderlineOffset: 3,
    cursor: "pointer",
  },
  markdownList: {
    margin: "0 0 16px",
    paddingLeft: 26,
    listStyle: "disc",
  },
  markdownOrderedList: {
    margin: "0 0 16px",
    paddingLeft: 26,
    listStyle: "decimal",
  },
  markdownListItem: {
    marginBottom: 4,
  },
  markdownTaskListItem: {
    display: "flex",
    alignItems: "flex-start",
    gap: 8,
    listStyle: "none",
  },
  markdownTaskCheckbox: {
    margin: "5px 0 0",
    flex: "0 0 auto",
  },
  markdownTaskContent: {
    minWidth: 0,
    flex: 1,
  },
  markdownBlockquote: {
    margin: "18px 0",
    padding: "2px 0 2px 16px",
    borderLeft: `3px solid ${colors.borderStrong}`,
    color: colors.textMuted,
  },
  markdownCode: {
    padding: "2px 5px",
    borderRadius: 8,
    background: colors.surfaceSubtle,
    fontFamily: fontFamilies.mono,
    fontSize: "0.9em",
  },
  markdownMathInline: {
    display: "inline-block",
    maxWidth: "100%",
    verticalAlign: "middle",
  },
  markdownMathBlock: {
    margin: "18px 0",
    overflowX: "auto",
    overflowY: "hidden",
  },
  markdownMathDisplay: {
    display: "block",
    minWidth: "max-content",
  },
  markdownMathErrorInline: {
    padding: "2px 5px",
    border: `1px solid ${colors.dangerBorder}`,
    background: colors.dangerSurface,
    color: colors.dangerStrong,
    fontFamily: fontFamilies.mono,
    fontSize: "0.9em",
  },
  markdownMathErrorDisplay: {
    display: "block",
    width: "max-content",
    minWidth: "100%",
    padding: "12px 14px",
    border: `1px solid ${colors.dangerBorder}`,
    background: colors.dangerSurface,
    color: colors.dangerStrong,
    fontFamily: fontFamilies.mono,
    fontSize: "0.9em",
    whiteSpace: "pre-wrap",
  },
  markdownPre: {
    margin: "18px 0",
    padding: "14px 16px",
    overflowX: "auto",
    border: `1px solid ${colors.border}`,
    borderRadius: 8,
    background: colors.surfaceSubtle,
    lineHeight: 1.55,
  },
  markdownRule: {
    margin: "28px 0",
    border: 0,
    borderTop: `1px solid ${colors.border}`,
  },
  markdownAttachmentReference: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    padding: "2px 7px",
    border: `1px solid ${colors.borderStrong}`,
    borderRadius: 8,
    background: colors.surfaceSubtle,
    color: colors.textMuted,
    fontSize: "0.92em",
    verticalAlign: "baseline",
  },
  markdownAttachmentImage: {
    display: "block",
    maxWidth: "100%",
    height: "auto",
    margin: "16px 0",
    borderRadius: 8,
  },
  markdownTableWrap: {
    margin: "18px 0",
    overflowX: "auto",
  },
  markdownTable: {
    width: "100%",
    borderCollapse: "collapse" as const,
    fontSize: 14,
  },
  markdownTableHeader: {
    padding: "9px 12px",
    border: `1px solid ${colors.border}`,
    background: colors.surfaceSubtle,
    fontWeight: 650,
    verticalAlign: "top",
  },
  markdownTableCell: {
    padding: "9px 12px",
    border: `1px solid ${colors.border}`,
    verticalAlign: "top",
  },
};
