import type { CSSProperties } from "react";
import { colors, fontFamilies, layout, shadows } from "./constants";

export const navigationStyles: Record<string, CSSProperties> = {
  topBar: {
    position: "relative",
    zIndex: 50,
    height: layout.topBarHeight,
    flexShrink: 0,
    display: "grid",
    gridTemplateColumns: "1fr minmax(260px, 480px) 1fr",
    alignItems: "center",
    gap: 20,
    padding: "0 20px",
    background: colors.glass,
    backdropFilter: "blur(8px)",
    borderBottom: `1px solid ${colors.border}`,
    boxSizing: "border-box",
  },
  topBarLeft: {
    display: "flex",
    alignItems: "center",
    gap: 18,
    minWidth: 0,
  },
  topBarRight: {
    minWidth: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 8,
  },
  topBarIconButton: {
    position: "relative",
    height: 32,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 2,
    padding: "0 7px",
    border: `1px solid ${colors.borderStrong}`,
    borderRadius: 8,
    background: colors.surfaceSubtle,
    color: colors.textMuted,
    font: "inherit",
    cursor: "pointer",
  },
  topBarUnreadBadge: {
    position: "absolute",
    top: -7,
    right: -8,
    minWidth: 17,
    height: 17,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "0 4px",
    border: `2px solid ${colors.glass}`,
    borderRadius: 9,
    background: colors.accent,
    color: colors.textOnStrong,
    fontFamily: fontFamilies.mono,
    fontSize: 9,
    fontWeight: 700,
    lineHeight: 1,
    boxSizing: "border-box",
  },
  createMenu: {
    position: "relative",
  },
  createMenuPopover: {
    position: "absolute",
    top: "calc(100% + 10px)",
    right: 0,
    zIndex: 30,
    width: 250,
    padding: 6,
    border: `1px solid ${colors.border}`,
    borderRadius: 8,
    background: colors.surface,
    boxShadow: shadows.medium,
  },
  createMenuLabel: {
    display: "block",
    padding: "7px 9px 6px",
    color: colors.textSubtle,
    fontFamily: fontFamilies.mono,
    fontSize: 10,
    fontWeight: 700,
    letterSpacing: "0.07em",
    textTransform: "uppercase",
  },
  createMenuHeader: {
    display: "flex",
    alignItems: "center",
    gap: 2,
    marginBottom: 4,
  },
  createMenuBackButton: {
    width: 28,
    height: 28,
    display: "inline-grid",
    placeItems: "center",
    padding: 0,
    border: 0,
    borderRadius: 8,
    background: colors.transparent,
    color: colors.textMuted,
    font: "inherit",
    fontSize: 16,
    cursor: "pointer",
  },
  createMenuList: {
    maxHeight: 300,
    overflowY: "auto",
    overscrollBehavior: "contain",
  },
  createMenuItem: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    padding: "8px 9px",
    border: 0,
    borderRadius: 8,
    background: colors.transparent,
    color: colors.text,
    font: "inherit",
    fontSize: 13,
    textAlign: "left",
    cursor: "pointer",
  },
  createMenuItemText: {
    minWidth: 0,
    display: "flex",
    flexDirection: "column",
    gap: 2,
  },
  createMenuItemDescription: {
    overflow: "hidden",
    color: colors.textSubtle,
    fontSize: 11,
    fontWeight: 400,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  createMenuDivider: {
    height: 1,
    margin: "5px 3px",
    background: colors.border,
  },
  createMenuCurrent: {
    color: colors.textSubtle,
    fontFamily: fontFamilies.mono,
    fontSize: 9,
    textTransform: "uppercase",
  },
  wordmarkButton: {
    padding: 0,
    border: 0,
    background: colors.transparent,
    color: "inherit",
    font: "inherit",
    fontWeight: 700,
    cursor: "pointer",
  },
  workspaceMenu: {
    position: "relative",
  },
  workspaceSwitcher: {
    minWidth: 0,
    maxWidth: "100%",
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "6px 8px",
    border: 0,
    borderRadius: 8,
    background: colors.transparent,
    color: colors.textMuted,
    font: "inherit",
    cursor: "pointer",
  },
  workspaceMenuPopover: {
    position: "absolute",
    top: "calc(100% + 8px)",
    left: 0,
    zIndex: 20,
    width: "min(340px, calc(100vw - 32px))",
    padding: 6,
    border: `1px solid ${colors.border}`,
    borderRadius: 8,
    background: colors.surface,
    boxShadow: shadows.medium,
  },
  workspaceMenuSearch: {
    width: "100%",
    height: 36,
    marginBottom: 6,
    padding: "0 10px",
    border: `1px solid ${colors.borderStrong}`,
    borderRadius: 8,
    background: colors.surfaceSubtle,
    color: colors.text,
    font: "inherit",
    outline: "none",
    boxSizing: "border-box",
  },
  workspaceMenuList: {
    maxHeight: 320,
    overflowY: "auto",
    overscrollBehavior: "contain",
  },
  workspaceMenuMessage: {
    padding: "12px 10px",
    color: colors.textMuted,
    fontSize: 13,
  },
  workspaceMenuError: {
    padding: "12px 10px",
    color: colors.dangerStrong,
    fontSize: 13,
  },
  workspaceMenuItem: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 16,
    padding: "9px 10px",
    border: 0,
    borderRadius: 8,
    background: colors.transparent,
    color: colors.text,
    textAlign: "left",
    font: "inherit",
    cursor: "pointer",
  },
  workspaceMenuItemActive: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 16,
    padding: "9px 10px",
    border: 0,
    borderRadius: 8,
    background: colors.surfaceSubtle,
    color: colors.text,
    textAlign: "left",
    font: "inherit",
    cursor: "pointer",
  },
  workspaceMenuItemHighlighted: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 16,
    padding: "9px 10px",
    border: 0,
    borderRadius: 8,
    background: colors.surfaceSelected,
    color: colors.text,
    textAlign: "left",
    font: "inherit",
    cursor: "pointer",
  },
  workspaceMenuItemText: {
    minWidth: 0,
    display: "flex",
    flexDirection: "column",
    gap: 2,
  },
  workspaceMenuItemDescription: {
    overflow: "hidden",
    color: colors.textSubtle,
    fontSize: 12,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  searchInputWrapper: {
    position: "relative",
    width: "100%",
  },
  searchInput: {
    width: "100%",
    height: 36,
    padding: "0 44px 0 14px",
    borderRadius: 8,
    border: `1px solid ${colors.borderStrong}`,
    background: colors.surfaceSubtle,
    color: colors.text,
    font: "inherit",
    outline: "none",
    boxSizing: "border-box",
  },
  searchShortcutKey: {
    position: "absolute",
    top: "50%",
    right: 10,
    minWidth: 20,
    height: 20,
    display: "inline-grid",
    placeItems: "center",
    padding: "0 4px",
    transform: "translateY(-50%)",
    border: `1px solid ${colors.borderStrong}`,
    borderRadius: 8,
    background: colors.surface,
    color: colors.textMuted,
    font: "inherit",
    fontSize: 11,
    lineHeight: 1,
    pointerEvents: "none",
  },
  userMenu: {
    position: "relative",
    justifySelf: "end",
  },
  userMenuTrigger: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: 0,
    border: 0,
    background: colors.transparent,
    color: colors.textMuted,
    font: "inherit",
    fontSize: 14,
    cursor: "pointer",
  },
  userMenuPopover: {
    position: "absolute",
    top: "calc(100% + 10px)",
    right: 0,
    zIndex: 30,
    width: 240,
    padding: 6,
    border: `1px solid ${colors.border}`,
    borderRadius: 8,
    background: colors.surface,
    boxShadow: shadows.medium,
  },
  userMenuIdentity: {
    minWidth: 0,
    display: "flex",
    flexDirection: "column",
    gap: 2,
    padding: "8px 10px",
    color: colors.text,
    fontSize: 13,
  },
  userMenuUsername: {
    overflow: "hidden",
    color: colors.textSubtle,
    fontSize: 12,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  userMenuDivider: {
    height: 1,
    margin: "4px 0",
    background: colors.surfaceMuted,
  },
  userMenuTheme: {
    padding: "7px 8px 8px",
  },
  userMenuThemeLabel: {
    display: "block",
    marginBottom: 6,
    color: colors.textSubtle,
    fontSize: 11,
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: "0.07em",
    fontFamily: fontFamilies.mono,
  },
  userMenuThemeOptions: {
    display: "grid",
    gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
    gap: 3,
    padding: 3,
    border: `1px solid ${colors.border}`,
    borderRadius: 8,
    background: colors.surfaceSubtle,
  },
  userMenuThemeOption: {
    padding: "5px 6px",
    border: 0,
    borderRadius: 8,
    background: colors.transparent,
    color: colors.textMuted,
    font: "inherit",
    fontSize: 11,
    cursor: "pointer",
  },
  userMenuThemeOptionActive: {
    padding: "5px 6px",
    border: `1px solid ${colors.border}`,
    borderRadius: 8,
    background: colors.surface,
    color: colors.text,
    font: "inherit",
    fontSize: 11,
    fontWeight: 600,
    cursor: "pointer",
  },
  userMenuItem: {
    width: "100%",
    padding: "8px 10px",
    border: 0,
    borderRadius: 8,
    background: colors.transparent,
    color: colors.textMuted,
    textAlign: "left",
    font: "inherit",
    fontSize: 13,
    cursor: "pointer",
  },
  avatar: {
    width: 32,
    height: 32,
    flexShrink: 0,
    borderRadius: "50%",
    display: "grid",
    placeItems: "center",
    background: colors.surfaceMuted,
    color: colors.text,
    fontSize: 13,
    fontWeight: 700,
  },
  workspaceChooser: {
    width: "100%",
    height: "100%",
    padding: "72px 32px",
    overflowY: "auto",
    boxSizing: "border-box",
  },
  contentPaneInner: {
    width: "100%",
    maxWidth: 1100,
    margin: "0 auto",
  },
  contentPaneInnerGraph: {
    width: "100%",
    height: "100%",
  },
  pageHeader: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    marginBottom: 36,
    paddingBottom: 20,
    borderBottom: `1px solid ${colors.borderStrong}`,
  },
  eyebrow: {
    margin: 0,
    color: colors.accent,
    fontFamily: fontFamilies.mono,
    fontSize: 12,
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: "0.08em",
  },
  pageTitle: {
    margin: 0,
    color: colors.text,
    fontSize: 34,
    lineHeight: 1.15,
    fontFamily: fontFamilies.display,
    fontWeight: 400,
    letterSpacing: "-0.025em",
  },
  workspaceChooserActions: {
    display: "flex",
    alignItems: "flex-end",
    justifyContent: "space-between",
    gap: 16,
    marginTop: -16,
    marginBottom: 24,
  },
  pinnedCardSection: {
    display: "flex",
    flexDirection: "column",
    gap: 10,
    marginTop: -12,
    marginBottom: 32,
  },
  pinnedCardHeader: {
    display: "flex",
    alignItems: "flex-end",
    justifyContent: "space-between",
    gap: 16,
  },
  pinnedCardGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(220px, 320px))",
    gap: 10,
  },
  pinnedCard: {
    position: "relative",
    minHeight: 112,
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    gap: 12,
    padding: 13,
    border: `1px solid ${colors.accentMuted}`,
    borderRadius: 8,
    background: colors.surface,
    boxShadow: shadows.small,
  },
  pinnedCardAction: {
    position: "absolute",
    inset: 0,
    zIndex: 0,
    padding: 0,
    border: 0,
    borderRadius: 8,
    background: colors.transparent,
    cursor: "pointer",
  },
  pinnedCardMain: {
    position: "relative",
    zIndex: 1,
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    gap: 6,
    paddingRight: 32,
    pointerEvents: "none",
  },
  pinnedCardPinAction: {
    position: "absolute",
    top: 11,
    right: 11,
    zIndex: 2,
  },
  pinnedCardFooter: {
    position: "relative",
    zIndex: 1,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    pointerEvents: "none",
  },
  workspaceGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(280px, 1fr))",
    gap: 0,
    borderTop: `1px solid ${colors.borderStrong}`,
    borderLeft: `1px solid ${colors.borderStrong}`,
  },
  workspaceCard: {
    minHeight: 160,
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    gap: 12,
    padding: 22,
    textAlign: "left",
    background: colors.surface,
    border: 0,
    borderRight: `1px solid ${colors.borderStrong}`,
    borderBottom: `1px solid ${colors.borderStrong}`,
    borderRadius: 8,
    color: colors.text,
    font: "inherit",
    cursor: "pointer",
  },
  workspaceName: {
    fontSize: 17,
    lineHeight: 1.35,
  },
  workspaceDescription: {
    color: colors.textMuted,
    lineHeight: 1.5,
  },
  workspaceStatus: {
    marginTop: "auto",
    color: colors.textSubtle,
    fontSize: 12,
    textTransform: "capitalize",
    fontFamily: fontFamilies.mono,
  },
  kivalShell: {
    flex: 1,
    minHeight: 0,
    display: "grid",
    gridTemplateColumns: `${layout.sidebarWidth}px minmax(0, 1fr)`,
    overflow: "hidden",
  },
  shell: {
    flex: 1,
    minHeight: 0,
    display: "grid",
    gridTemplateColumns: `${layout.sidebarWidth}px minmax(0, 1fr)`,
    overflow: "hidden",
  },
  shellWithContext: {
    flex: 1,
    minHeight: 0,
    display: "grid",
    gridTemplateColumns: `${layout.sidebarWidth}px minmax(0, 1fr) ${layout.contextPanelWidth}px`,
    overflow: "hidden",
  },
  sidebar: {
    height: "100%",
    minHeight: 0,
    display: "flex",
    flexDirection: "column",
    overflow: "visible",
    padding: "20px 12px",
    background: colors.background,
    borderRight: `1px solid ${colors.border}`,
    boxSizing: "border-box",
  },
  nav: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
  },
  sidebarNavigation: {
    minHeight: 0,
    flex: 1,
    overflowY: "auto",
  },
  navItem: {
    width: "100%",
    padding: "9px 10px",
    textAlign: "left",
    border: 0,
    borderRadius: 8,
    background: colors.transparent,
    color: colors.textMuted,
    font: "inherit",
    cursor: "pointer",
  },
  navItemActive: {
    width: "100%",
    padding: "9px 10px",
    textAlign: "left",
    border: 0,
    borderRadius: 8,
    background: colors.surfaceSelected,
    color: colors.text,
    font: "inherit",
    fontWeight: 600,
    cursor: "pointer",
  },
  sidebarSection: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
    marginTop: 32,
  },
  sidebarLabel: {
    margin: "0 10px 8px",
    color: colors.textSubtle,
    fontSize: 11,
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: "0.08em",
    fontFamily: fontFamilies.mono,
  },
  mainContent: {
    minWidth: 0,
    height: "100%",
    padding: "42px 48px",
    overflowY: "auto",
    background: colors.surface,
    boxSizing: "border-box",
  },
  mainContentGraph: {
    minWidth: 0,
    height: "100%",
    overflow: "hidden",
    background: colors.surface,
  },
  sectionHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 16,
    marginBottom: 12,
  },
  sectionTitle: {
    margin: 0,
    color: colors.text,
    fontSize: 18,
    lineHeight: 1.3,
  },
  sectionActions: {
    display: "flex",
    alignItems: "center",
    gap: 12,
  },
  commandPaletteBackdrop: {
    position: "fixed",
    inset: 0,
    zIndex: 1000,
    display: "flex",
    justifyContent: "center",
    alignItems: "flex-start",
    paddingTop: "12vh",
    background: colors.overlay,
    backdropFilter: "blur(2px)",
  },
  commandPalette: {
    width: "min(620px, calc(100vw - 32px))",
    maxHeight: "min(520px, 72vh)",
    overflow: "hidden",
    background: colors.surface,
    border: `1px solid ${colors.borderStrong}`,
    borderRadius: 8,
    boxShadow: shadows.large,
  },
  commandPaletteSearchRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "14px 16px",
    color: colors.textMuted,
    borderBottom: `1px solid ${colors.border}`,
  },
  commandPaletteInput: {
    flex: 1,
    minWidth: 0,
    border: 0,
    outline: "none",
    background: colors.transparent,
    color: colors.text,
    font: "inherit",
    fontSize: 15,
  },
  commandPaletteKey: {
    padding: "2px 6px",
    border: `1px solid ${colors.borderStrong}`,
    borderRadius: 8,
    background: colors.surfaceSubtle,
    color: colors.textSubtle,
    fontSize: 11,
    fontFamily: "inherit",
  },
  commandPaletteResults: {
    display: "flex",
    flexDirection: "column",
    gap: 2,
    maxHeight: "min(440px, 62vh)",
    overflowY: "auto",
    padding: 6,
  },
  commandPaletteItem: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 16,
    width: "100%",
    padding: "10px 11px",
    border: 0,
    borderRadius: 8,
    background: colors.transparent,
    color: colors.text,
    font: "inherit",
    textAlign: "left",
    cursor: "pointer",
  },
  commandPaletteItemActive: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 16,
    width: "100%",
    padding: "10px 11px",
    border: 0,
    borderRadius: 8,
    background: colors.surfaceSelected,
    color: colors.text,
    font: "inherit",
    textAlign: "left",
    cursor: "pointer",
  },
  commandPaletteHint: {
    color: colors.textSubtle,
    fontSize: 12,
  },
  commandPaletteEmpty: {
    padding: "24px 12px",
    color: colors.textSubtle,
    textAlign: "center",
    fontSize: 13,
  },
};
