import type { CSSProperties } from "react";
import { colors, layout, shadows } from "./constants";

export const objectsStyles: Record<string, CSSProperties> = {
  objectHeader: {
    maxWidth: layout.objectContentMaxWidth,
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 24,
  },
  objectShareAvatarButton: {
    display: "inline-flex",
    alignItems: "center",
    padding: "2px 2px 2px 8px",
    border: 0,
    background: colors.transparent,
    font: "inherit",
    cursor: "pointer",
  },
  objectShareAvatars: {
    display: "flex",
    alignItems: "center",
  },
  objectShareAvatar: {
    position: "relative",
    width: 28,
    height: 28,
    marginLeft: -7,
    display: "grid",
    placeItems: "center",
    border: `2px solid ${colors.surface}`,
    borderRadius: "50%",
    background: colors.accentMuted,
    color: colors.text,
    fontSize: 10,
    fontWeight: 800,
    boxSizing: "border-box",
  },
  objectShareAvatarOverflow: {
    width: 28,
    height: 28,
    marginLeft: -7,
    display: "grid",
    placeItems: "center",
    border: `2px solid ${colors.surface}`,
    borderRadius: "50%",
    background: colors.surfaceMuted,
    color: colors.textMuted,
    fontSize: 9,
    fontWeight: 800,
    boxSizing: "border-box",
  },
  directoryHeaderActions: {
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 12,
  },
  directoryList: {
    border: `1px solid ${colors.border}`,
    borderRadius: 8,
    overflow: "hidden",
    background: colors.surface,
  },
  directoryRow: {
    minHeight: 68,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 20,
    padding: "12px 16px",
    borderBottom: `1px solid ${colors.surfaceMuted}`,
    background: colors.surface,
  },
  directoryIdentity: {
    minWidth: 0,
    display: "flex",
    alignItems: "center",
    gap: 12,
  },
  directoryAvatar: {
    width: 34,
    height: 34,
    flexShrink: 0,
    display: "grid",
    placeItems: "center",
    borderRadius: "50%",
    background: colors.surfaceMuted,
    color: colors.textMuted,
    fontSize: 12,
    fontWeight: 700,
  },
  directoryMain: {
    minWidth: 0,
    display: "flex",
    flexDirection: "column",
    gap: 4,
  },
  directoryRowAction: {
    position: "absolute",
    inset: 0,
    zIndex: 0,
    padding: 0,
    border: 0,
    background: colors.transparent,
    cursor: "pointer",
  },
  directoryRole: {
    flexShrink: 0,
    padding: "4px 8px",
    borderRadius: 8,
    border: `1px solid ${colors.border}`,
    background: colors.surfaceSubtle,
    color: colors.textMuted,
    fontSize: 12,
    textTransform: "capitalize",
  },
  objectList: {
    position: "relative",
    border: 0,
    borderRadius: 8,
    overflow: "visible",
    background: colors.surface,
  },
  objectRow: {
    width: "100%",
    minWidth: 0,
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 20,
    padding: "14px 16px",
    background: colors.surface,
    border: 0,
    borderBottom: `1px solid ${colors.surfaceMuted}`,
    color: colors.text,
    textAlign: "left",
    font: "inherit",
    cursor: "pointer",
  },
  objectMain: {
    minWidth: 0,
    display: "flex",
    flexDirection: "column",
    gap: 5,
  },
  objectMeta: {
    color: colors.textSubtle,
    fontSize: 13,
  },
  searchSnippet: {
    maxWidth: 720,
    color: colors.textMuted,
    fontSize: 13,
    lineHeight: 1.5,
  },
  objectStatus: {
    flexShrink: 0,
    color: colors.textMuted,
    fontSize: 12,
    textTransform: "capitalize",
  },
  emptyState: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    padding: 32,
    color: colors.textMuted,
  },
  contextPanel: {
    height: "100%",
    padding: "24px 18px",
    overflowY: "auto",
    background: colors.surfaceSubtle,
    borderLeft: `1px solid ${colors.border}`,
    boxSizing: "border-box",
  },
  contextBlock: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    padding: "16px 10px",
    borderBottom: `1px solid ${colors.surfaceMuted}`,
  },
  backButton: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    marginBottom: 28,
    padding: 0,
    border: 0,
    background: colors.transparent,
    color: colors.textMuted,
    font: "inherit",
    cursor: "pointer",
  },
  objectContent: {
    maxWidth: layout.objectContentMaxWidth,
    marginBottom: 36,
    color: colors.text,
    fontSize: 16,
    lineHeight: 1.7,
  },
  objectBody: {
    margin: 0,
    whiteSpace: "pre-wrap",
    overflowWrap: "anywhere",
    fontFamily: "inherit",
    fontSize: 16,
    lineHeight: 1.7,
  },
  metadataSection: {
    maxWidth: layout.objectContentMaxWidth,
    marginBottom: 32,
  },
  metadataGrid: {
    marginTop: 12,
    border: `1px solid ${colors.border}`,
    borderRadius: 8,
    overflow: "hidden",
    background: colors.surface,
  },
  metadataRow: {
    display: "grid",
    gridTemplateColumns: "180px minmax(0, 1fr)",
    gap: 16,
    padding: "10px 14px",
    borderBottom: `1px solid ${colors.surfaceMuted}`,
  },
  metadataKey: {
    color: colors.textSubtle,
  },
  contextHeading: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  contextCount: {
    color: colors.textSubtle,
    fontSize: 12,
  },
  connectionList: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
  },
  connectionItem: {
    width: "100%",
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    gap: 3,
    padding: "10px 10px",
    border: 0,
    borderRadius: 8,
    background: colors.transparent,
    color: colors.text,
    textAlign: "left",
    font: "inherit",
    cursor: "pointer",
  },
  connectionTitle: {
    fontSize: 13,
    lineHeight: 1.35,
  },
  connectionType: {
    color: colors.textSubtle,
    fontSize: 11,
    textTransform: "capitalize",
  },
  versionHistory: {
    maxWidth: layout.objectContentMaxWidth,
    marginTop: 24,
  },
  versionHistoryToggle: {
    display: "inline-flex",
    alignItems: "center",
    gap: 4,
    padding: 0,
    border: 0,
    background: colors.transparent,
    color: colors.textMuted,
    font: "inherit",
    fontSize: 13,
    cursor: "pointer",
  },
  versionHistoryList: {
    display: "flex",
    flexDirection: "column",
    gap: 2,
    marginTop: 10,
    paddingLeft: 10,
    borderLeft: `1px solid ${colors.border}`,
  },
  versionHistoryItem: {
    width: "100%",
    display: "flex",
    justifyContent: "space-between",
    gap: 16,
    padding: "6px 8px",
    border: 0,
    borderRadius: 8,
    background: colors.transparent,
    color: colors.textMuted,
    textAlign: "left",
    font: "inherit",
    fontSize: 12,
    cursor: "pointer",
  },
  versionHistoryItemActive: {
    width: "100%",
    display: "flex",
    justifyContent: "space-between",
    gap: 16,
    padding: "6px 8px",
    border: 0,
    borderRadius: 8,
    background: colors.surfaceSubtle,
    color: colors.text,
    textAlign: "left",
    font: "inherit",
    fontSize: 12,
    cursor: "pointer",
  },
  versionHistoryMeta: {
    color: colors.textSubtle,
    whiteSpace: "nowrap",
  },
  contextAction: {
    alignSelf: "flex-start",
    padding: 0,
    border: 0,
    background: colors.transparent,
    color: colors.textMuted,
    font: "inherit",
    fontSize: 12,
    cursor: "pointer",
  },
  connectionEditor: {
    display: "flex",
    flexDirection: "column",
    gap: 12,
    marginTop: 8,
  },
  connectionEditorActions: {
    display: "flex",
    justifyContent: "flex-end",
    gap: 8,
  },
  connectionRow: {
    display: "flex",
    alignItems: "stretch",
  },
  connectionRemove: {
    width: 28,
    flexShrink: 0,
    border: 0,
    background: colors.transparent,
    color: colors.textSubtle,
    font: "inherit",
    fontSize: 18,
    cursor: "pointer",
  },
  dangerButton: {
    minHeight: 36,
    padding: "0 14px",
    border: `1px solid ${colors.dangerBorder}`,
    borderRadius: 8,
    background: colors.dangerSurface,
    color: colors.dangerStrong,
    font: "inherit",
    fontSize: 14,
    fontWeight: 600,
    cursor: "pointer",
  },
  metadataEditor: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
  },
  metadataEditorRow: {
    display: "grid",
    gridTemplateColumns: "minmax(140px, 0.8fr) minmax(0, 1.2fr) 32px",
    gap: 8,
    alignItems: "center",
  },
  metadataEditorKey: {
    height: 38,
    minWidth: 0,
    padding: "0 10px",
    borderRadius: 8,
    border: `1px solid ${colors.borderStrong}`,
    background: colors.surface,
    color: colors.text,
    font: "inherit",
    fontSize: 14,
    outline: "none",
    boxSizing: "border-box",
  },
  metadataEditorValue: {
    height: 38,
    minWidth: 0,
    padding: "0 10px",
    borderRadius: 8,
    border: `1px solid ${colors.borderStrong}`,
    background: colors.surface,
    color: colors.text,
    font: "inherit",
    fontSize: 14,
    outline: "none",
    boxSizing: "border-box",
  },
  metadataEditorRemove: {
    width: 32,
    height: 32,
    border: 0,
    borderRadius: 8,
    background: colors.transparent,
    color: colors.textSubtle,
    font: "inherit",
    fontSize: 18,
    cursor: "pointer",
  },
  metadataEditorAdd: {
    alignSelf: "flex-start",
    padding: 0,
    border: 0,
    background: colors.transparent,
    color: colors.textMuted,
    font: "inherit",
    fontSize: 13,
    cursor: "pointer",
  },
  objectActivity: {
    maxWidth: layout.objectContentMaxWidth,
    marginTop: 14,
  },
  objectActivityList: {
    display: "flex",
    flexDirection: "column",
    gap: 2,
    marginTop: 10,
    paddingLeft: 10,
    borderLeft: `1px solid ${colors.border}`,
  },
  objectActivityItem: {
    display: "flex",
    gap: 16,
    padding: "8px",
    color: colors.textMuted,
    fontSize: 12,
  },
  objectActivityMain: {
    minWidth: 0,
    display: "flex",
    flexDirection: "column",
    gap: 2,
  },
  objectActivityMeta: {
    color: colors.textSubtle,
  },
  objectActivityDetails: {
    color: colors.textMuted,
    lineHeight: 1.4,
  },
  objectRowMainAction: {
    minWidth: 0,
    flex: 1,
    display: "flex",
    alignItems: "center",
    padding: 0,
    border: 0,
    background: colors.transparent,
    color: "inherit",
    textAlign: "left",
    font: "inherit",
    cursor: "pointer",
  },
  objectRowActions: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    flexShrink: 0,
  },
  objectOverviewActions: {
    position: "relative",
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    flexShrink: 0,
    pointerEvents: "none",
  },
  objectOverviewMain: {
    position: "relative",
    minWidth: 0,
    flex: 1,
    display: "flex",
    flexDirection: "column",
    gap: 5,
    pointerEvents: "none",
  },
  objectTitleLine: {
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  objectOverviewRowAction: {
    position: "absolute",
    inset: 0,
    zIndex: 0,
    padding: 0,
    border: 0,
    background: colors.transparent,
    cursor: "pointer",
  },
  objectOverviewId: {
    fontSize: 12,
  },
  objectUpdatedBy: {
    color: colors.textSubtle,
    fontSize: 12,
  },
  objectActionsMenu: {
    position: "relative",
  },
  objectActionsTrigger: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: 34,
    height: 34,
    border: `1px solid ${colors.borderStrong}`,
    borderRadius: 8,
    background: colors.surface,
    color: colors.textMuted,
    font: "inherit",
    cursor: "pointer",
  },
  objectActionsPopover: {
    position: "absolute",
    top: 40,
    right: 0,
    zIndex: 30,
    display: "flex",
    flexDirection: "column",
    minWidth: 180,
    padding: 5,
    border: `1px solid ${colors.borderStrong}`,
    borderRadius: 8,
    background: colors.surface,
    boxShadow: shadows.medium,
  },
  objectActionsItem: {
    padding: "9px 10px",
    border: 0,
    borderRadius: 8,
    background: colors.transparent,
    color: colors.text,
    font: "inherit",
    textAlign: "left",
    cursor: "pointer",
  },
  objectActionsDanger: {
    padding: "9px 10px",
    border: 0,
    borderRadius: 8,
    background: colors.transparent,
    color: colors.danger,
    font: "inherit",
    textAlign: "left",
    cursor: "pointer",
  },
  objectActionsDivider: {
    height: 1,
    margin: "4px 5px",
    background: colors.surfaceMuted,
  },

  objectRowSelected: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 16,
    width: "100%",
    padding: "13px 14px",
    border: `1px solid ${colors.borderStrong}`,
    borderRadius: 8,
    background: colors.surfaceSelected,
    color: "inherit",
    font: "inherit",
    textAlign: "left",
    cursor: "pointer",
  },
  searchHighlight: {
    padding: 0,
    background: colors.highlight,
    color: "inherit",
    borderRadius: 2,
  },

  connectionTargetResults: {
    display: "flex",
    flexDirection: "column",
    gap: 3,
    maxHeight: 220,
    overflowY: "auto",
    padding: 4,
    border: `1px solid ${colors.border}`,
    borderRadius: 8,
    background: colors.surfaceSubtle,
  },
  connectionTargetResult: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    gap: 2,
    padding: "8px 9px",
    border: 0,
    borderRadius: 8,
    background: colors.transparent,
    color: colors.text,
    font: "inherit",
    textAlign: "left",
    cursor: "pointer",
  },
  connectionTargetSelected: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    padding: "9px 10px",
    border: `1px solid ${colors.borderStrong}`,
    borderRadius: 8,
    background: colors.surfaceSelected,
  },
  connectionTargetText: {
    display: "flex",
    flexDirection: "column",
    minWidth: 0,
  },
  connectionTargetClear: {
    border: 0,
    background: colors.transparent,
    color: colors.textSubtle,
    font: "inherit",
    fontSize: 18,
    cursor: "pointer",
  },
  commentaryPanel: {
    maxWidth: layout.objectContentMaxWidth,
    display: "flex",
    flexDirection: "column",
    gap: 14,
    marginTop: 30,
    paddingTop: 22,
    borderTop: `1px solid ${colors.border}`,
  },
  commentaryHeadingRow: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 20,
  },
  commentaryDescription: {
    margin: "3px 0 0",
    color: colors.textMuted,
    fontSize: 13,
    lineHeight: 1.4,
  },
  commentaryCount: {
    flexShrink: 0,
    color: colors.textSubtle,
    fontSize: 13,
  },
  commentaryComposer: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    padding: 11,
    border: `1px solid ${colors.border}`,
    borderRadius: 8,
    background: colors.surfaceSubtle,
  },
  commentaryComposerLabel: {
    display: "flex",
    flexDirection: "column",
    gap: 5,
    color: colors.text,
    fontSize: 13,
    fontWeight: 650,
  },
  commentaryTextareaWrap: {
    position: "relative",
  },
  commentaryTextarea: {
    width: "100%",
    minHeight: 72,
    resize: "vertical",
    padding: "8px 10px",
    border: `1px solid ${colors.borderStrong}`,
    borderRadius: 8,
    background: colors.surface,
    color: colors.text,
    font: "inherit",
    fontSize: 13,
    lineHeight: 1.5,
    boxSizing: "border-box",
  },
  commentaryMentionMenu: {
    position: "absolute",
    zIndex: 20,
    top: "calc(100% + 6px)",
    left: 0,
    right: 0,
    maxHeight: 220,
    overflowY: "auto",
    padding: 6,
    border: `1px solid ${colors.borderStrong}`,
    borderRadius: 8,
    background: colors.surface,
    boxShadow: "0 10px 28px rgba(0, 0, 0, 0.16)",
  },
  commentaryMentionMenuStatus: {
    display: "block",
    padding: "8px 9px",
    color: colors.textSubtle,
    fontSize: 12,
  },
  commentaryMentionOption: {
    width: "100%",
    display: "flex",
    alignItems: "baseline",
    gap: 8,
    padding: "7px 9px",
    border: 0,
    borderRadius: 6,
    background: colors.transparent,
    color: colors.text,
    font: "inherit",
    fontSize: 13,
    textAlign: "left",
    cursor: "pointer",
  },
  commentaryMentionOptionActive: {
    width: "100%",
    display: "flex",
    alignItems: "baseline",
    gap: 8,
    padding: "7px 9px",
    border: 0,
    borderRadius: 6,
    background: colors.surfaceMuted,
    color: colors.text,
    font: "inherit",
    fontSize: 13,
    textAlign: "left",
    cursor: "pointer",
  },
  commentaryComposerFooter: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  commentaryHint: {
    margin: 0,
    color: colors.textSubtle,
    fontSize: 12,
    lineHeight: 1.45,
  },
  commentaryActions: {
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 6,
  },
  commentaryThreadList: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
  },
  commentaryThread: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    padding: 10,
    border: `1px solid ${colors.border}`,
    borderRadius: 8,
    background: colors.surface,
  },
  commentaryThreadCollapsed: {
    minWidth: 0,
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "7px 8px 7px 10px",
    border: `1px solid ${colors.border}`,
    borderRadius: 8,
    background: colors.surface,
  },
  commentaryThreadSummary: {
    minWidth: 0,
    flex: 1,
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: 0,
    border: 0,
    background: colors.transparent,
    color: colors.text,
    font: "inherit",
    textAlign: "left",
    cursor: "pointer",
  },
  commentaryThreadSummaryText: {
    minWidth: 0,
    overflow: "hidden",
    color: colors.textMuted,
    fontSize: 13,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  commentaryThreadHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  commentaryOpenBadge: {
    padding: "2px 6px",
    borderRadius: 999,
    background: colors.accentMuted,
    color: colors.text,
    fontSize: 10,
    fontWeight: 700,
  },
  commentaryResolvedBadge: {
    padding: "2px 6px",
    borderRadius: 999,
    background: colors.surfaceMuted,
    color: colors.textMuted,
    fontSize: 10,
    fontWeight: 700,
  },
  commentaryComments: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
  },
  commentaryRootComment: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
  },
  commentaryReply: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
    marginLeft: 16,
    padding: "9px 11px",
    border: `1px solid ${colors.surfaceMuted}`,
    borderLeft: `2px solid ${colors.surfaceMuted}`,
    borderRadius: 8,
    background: colors.surfaceSubtle,
  },
  commentaryTargetComment: {
    padding: "9px 11px",
    borderRadius: 8,
    outline: `1px solid ${colors.accent}`,
    outlineOffset: 2,
  },
  commentaryCommentHeader: {
    display: "flex",
    alignItems: "baseline",
    justifyContent: "space-between",
    gap: 12,
  },
  commentaryAuthorBlock: {
    minWidth: 0,
    display: "flex",
    alignItems: "baseline",
    gap: 7,
    color: colors.text,
    fontSize: 13,
  },
  commentaryMeta: {
    color: colors.textSubtle,
    fontSize: 12,
  },
  commentaryBody: {
    margin: 0,
    color: colors.text,
    fontSize: 14,
    lineHeight: 1.55,
    whiteSpace: "pre-wrap",
    overflowWrap: "anywhere",
  },
  commentaryTombstone: {
    margin: 0,
    color: colors.textSubtle,
    fontSize: 13,
    fontStyle: "italic",
  },
  commentaryMentions: {
    display: "flex",
    flexWrap: "wrap",
    gap: 5,
  },
  commentaryMention: {
    padding: "2px 6px",
    borderRadius: 999,
    background: colors.surfaceMuted,
    color: colors.textMuted,
    fontSize: 11,
  },
  tertiaryButton: {
    padding: "5px 7px",
    border: 0,
    background: colors.transparent,
    color: colors.textMuted,
    font: "inherit",
    fontSize: 13,
    cursor: "pointer",
  },
  tertiaryDangerButton: {
    padding: "5px 7px",
    border: 0,
    background: colors.transparent,
    color: colors.danger,
    font: "inherit",
    fontSize: 13,
    cursor: "pointer",
  },
  inlineError: {
    margin: 0,
    color: colors.danger,
    fontSize: 13,
    lineHeight: 1.45,
  },
};
