import type { CSSProperties } from "react";
import { colors, shadows } from "./constants";

export const settingsStyles: Record<string, CSSProperties> = {
  settingsForm: {
    maxWidth: 720,
    display: "flex",
    flexDirection: "column",
    gap: 40,
  },
  settingsSection: {
    display: "flex",
    flexDirection: "column",
    gap: 18,
  },
  settingsSectionHeader: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
    marginBottom: 4,
  },
  settingsTextarea: {
    width: "100%",
    minHeight: 96,
    resize: "vertical",
    padding: "10px 12px",
    border: `1px solid ${colors.borderStrong}`,
    borderRadius: 8,
    background: colors.surface,
    color: colors.text,
    font: "inherit",
    lineHeight: 1.5,
  },
  settingsActions: {
    display: "flex",
    justifyContent: "flex-end",
    paddingTop: 4,
  },
  modalBackdrop: {
    position: "fixed",
    inset: 0,
    zIndex: 100,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 24,
    border: 0,
    background: colors.overlayStrong,
    font: "inherit",
    textAlign: "initial",
  },
  modalBackdropDismiss: {
    position: "absolute",
    inset: 0,
    border: 0,
    padding: 0,
    background: colors.transparent,
    cursor: "default",
  },
  modalDialog: {
    position: "relative",
    zIndex: 1,
    width: "min(100%, 440px)",
    display: "flex",
    flexDirection: "column",
    gap: 20,
    padding: 22,
    border: `1px solid ${colors.border}`,
    borderRadius: 8,
    background: colors.surface,
    boxShadow: shadows.large,
  },
  modalCopy: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
  },
  modalTitle: {
    margin: 0,
    color: colors.text,
    fontSize: 18,
    lineHeight: 1.3,
  },
  modalActions: {
    display: "flex",
    justifyContent: "flex-end",
    gap: 8,
  },
};
