[profile.default]
retries = { backoff = "exponential", count = 2, delay = "2s", jitter = true }
slow-timeout = { period = "30s", terminate-after = 2 }

[[profile.default.overrides]]
filter = "binary(stateful)"
retries = 0
slow-timeout = { period = "1h", terminate-after = 2 }
